### ISSUE TITLE
ics/ical script support for multiple calendars

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/Google-Apps-Script-Library#10]
The argument here is to add support for multiple ics/ical calendars to be imported into the same calendar

**Comment by oceanmedianow** [comment]
That would be awesome!!!!!!

I am getting an error on line 137. 
Action not allowed (line 137, file "Code")Dismiss

Any insight

**Comment by derekantrican** [comment]
@oceanmedianow This issue thread is not the place to discuss case-by-case problems. Please email me at derekantrican@gmail.com

**Comment by derekantrican** [comment]
Kamino closed and cloned this issue to derekantrican/GAS-ICS-Sync
