### ISSUE TITLE
ical sync script for (webcal?) facebook on google cal?

### ISSUE THREAD

**Issue by LeoUfimtsev** [derekantrican/Google-Apps-Script-Library#11]
Hello, 

I'm trying to use the ics/ical sync script:
https://script.google.com/a/redhat.com/d/1QeZFLSM1EkuFvYcryECI_xH-IZVe1-IxGRq_n6OoXp1CmVtSeTeigEx4/edit?usp=drive_web

To sync my Facebook calendar (more frequently) into my google calendar. (atm it does it once every 6-12 hours).

From FB, I get a url like this:
webcal://www.facebook.com/ical/u.php?uid=1000......

But when I try to run the script with the above url, it tells me that it's not valid url.

Is there away to get this to work?

**Comment by derekantrican** [comment]
@LeoUfimtsev please email me at derekantrican@gmail.com and I can help you troubleshoot this

**Comment by derekantrican** [comment]
@LeoUfimtsev try removing the `webcal://` portion of your url

**Comment by derekantrican** [comment]
This specific issue has been fixed (the issue was the `webcal://` string at the beginning). @LeoUfimtsev is still having a problem with the description which could be related to #7
