### ISSUE TITLE
Error with ICal sync script

### ISSUE THREAD

**Issue by baustin27** [derekantrican/Google-Apps-Script-Library#3]
Getting?

TypeError: Cannot find function getEvents in object . (line 188, file "Code")

**Comment by derekantrican** [comment]
Sorry you're having issues @baustin27 

Can you give me what you have for line 12 (the `targetCalendarName` line)?

Also, if you could make a copy of this script and run it for me, that'd be helpful: https://script.google.com/d/1jVipNM6Ebvmju2oaYHebBC_IKJOqGuFBVJLDWLi_C2z9ITmZpOPMGeOE/edit?usp=sharing

**Comment by derekantrican** [comment]
@baustin27 Any update? If not, I'll be closing this issue soon

**Comment by derekantrican** [comment]
Closing this because of a lack of information
