### ISSUE TITLE
ICS/ICAL sync timezone issue

### ISSUE THREAD

**Issue by derekantrican** [derekantrican/Google-Apps-Script-Library#6]
The following function is having trouble parsing timezones and needs to be improved:

    function GetUTCTime(parameter){
      parameter = parameter.substr(1); //Remove leading ; or : character
      if (parameter.includes("TZID")){
        var tzid = parameter.split("TZID=")[1].split(":")[0];
        var time = parameter.split(":")[1];
        return Moment.moment.tz(time,tzid).tz("Etc/UTC").format("YYYYMMDDTHHmmss") + "Z";    
      }
      else
        return parameter;
    }

The solution is to use regex to parse out the parts of the string. Here is documentation on how this parameter is formatted: https://www.kanzaki.com/docs/ical/dtstart.html

**Comment by derekantrican** [comment]
Some regex's: https://regex101.com/r/Nstcrr/3

**Comment by jasmith1317** [comment]
Is this the issue that is causing it to place all of the events on one day at the same time?  I just installed it and started running it today to see if it worked.

**Comment by jasmith1317** [comment]
@derekantrican I am using just a test calendar with three made up events on it from Outlook Online (Office365). I'll add in the ics, but it appears as though it's just not parsing the Date and Time info properly.  
[calendar (1).txt](https://github.com/derekantrican/Google-Apps-Script-Library/files/1876672/calendar.1.txt)

For the DTSTART and DTEND the format of the ics file is as follows:
DTSTART;TZID="(UTC-05:00) Indiana (East)":20180404T120000
DTEND;TZID="(UTC-05:00) Indiana (East)":20180404T130000

One of my colleagues is also taking a look at it and your script to see if he can't figure it out also. I'm not much into js though myself, but we do have a use case for something like this since Google can't seem to get the job done after almost 5 years of complaints.

**Comment by jasmith1317** [comment]
@derekantrican Also, it looks like the actual ics url we are trying to use is even formatted differently than that now that I've looked at it closer.  I'm trying to get the url of the actual calendar we will be using so that we can try to workout the calendar we would actually be using.

**Comment by jasmith1317** [comment]
@derekantrican Ok so here is one of the production ics files and a link to it....
[sports-all.txt](https://github.com/derekantrican/Google-Apps-Script-Library/files/1877145/sports-all.txt)
http://msdwarren.blob.core.windows.net/calendar/sports-all.ics

This one actually works and imports the events at the correct times, but it inserts "\" into the Title of the event and then every place in the description there is a "\n" it does not start a new line and instead inserts the "\n" and drops part of the description. 
![image](https://user-images.githubusercontent.com/38076265/38327750-fef34882-3816-11e8-91e9-c8e10144d167.png)
 My colleague has looked at it some today, but hasn't been able to figure it out yet either.  Finally, we noticed the script is supposed to be checking the ID before it imports events, but in some cases it is duplicating the event not every event does this happen to though.

**Comment by derekantrican** [comment]
@jasmith1317 I downloaded the ics file from the link that you provided. It looks like the title and description are that way in the file:

    BEGIN:VEVENT
    CREATED;VALUE=DATE:19000101
    DESCRIPTION:Start Time: 5:30 PM\nEnd Time: 7:30 PM\nSport: Baseball\nGender
     : Male\nClass(es): V\nLocation: Lawrence North\nOpponent(s): Lawrence Nort
     h High School
    DTEND:20190410T233000Z
    DTSTART:20190410T213000Z
    DTSTAMP:20180404T055405Z
    LAST-MODIFIED;VALUE=DATE:19000101
    LOCATION:Lawrence North
    SEQUENCE:0
    SUMMARY:Baseball\, Varsity @ Lawrence North
    TRANSP:Transparent
    UID:e3020681
    END:VEVENT

My program parses the ics file line by line, so that's why the description is getting cut off (because the ics file here has the description split onto multiple lines). I can probably look into adjusting the program to account for this. I'll also look into why the `\n` isn't getting treated properly.

*This isn't really the place for extended discussion on an unrelated topic, so I'll be moving that elsewhere soon*

**Comment by derekantrican** [comment]
Kamino cloned this issue to derekantrican/GAS-ICS-Sync
