### ISSUE TITLE
ical/ics url Caching issue

### ISSUE THREAD

**Issue by jimmysingla** [derekantrican/Google-Apps-Script-Library#8]
This is a great library to use for continuous sync with google calendar. I was using it and found few issues. Don't know whether these issues are general or only for me. One of these issues is : The URL that I am using to profile ical/ics file, got cached in this script. I noticed this issue while i was testing by adding new events in file and trying to sync it with Google Calendar. New events are not captured.

I found and applied a solution for this. I would like to share and discuss it with you. If you allow me to commit my updates to your repo that would be help full to someone too. And we can discuss and solve issues further. :)

Again this script is Nice and saved lots of my time. Thanks!

**Comment by derekantrican** [comment]
@jimmysingla I suggest you fork this repository, make your changes, then make a pull request: https://help.github.com/articles/creating-a-pull-request-from-a-fork/ . Then I'll review the changes you're suggesting

**Comment by derekantrican** [comment]
Kamino cloned this issue to derekantrican/GAS-ICS-Sync

**Comment by derekantrican** [comment]
@jimmysingla This issue has now moved to the new repository here: https://github.com/derekantrican/GAS-ICS-Sync/issues/5 . If you have any suggestions, please fork that repository, make your changes, and start a pull request

**Comment by jimmysingla** [comment]
Thanks for informing me regarding this.
